Data_Warehouse_Path: E:\Data            #数据库路径
Data_Must_Need: [close, market_cap]

Independent_Variable: ['000300']        #要分析的对象
Industry_Class: [sw_l1]                 #行业分类方法



Analyse_Start_date: '2015-01-01'
Analyse_End_date: '2021-01-24'